In [1]:
import sys
import pandas as pd
from IPython.display import display
pd.options.display.max_columns = None

sys.path.append('F:/repo/gpsbeam')

from src.config.data_config import DataConfig
from src.config.cnn_ed_rnn_model_config import ModelConfig
from src.config.experiment_config import ExperimentConfig
from src.experiment import RunExperiment


In [2]:
run_obj = RunExperiment(data_config =DataConfig(scenario_num=23,
                                                splitting_method='adjusted',
                                                train_val_test_split_frac=[0.65,0.15, 0.2],
                                                seednum=42
                                                ), 
              model_config=ModelConfig(model_arch_name='cnn-ed-gru-model',
                                       train_epoch=20,
                                       train_batch_size=8,
                                       test_batch_size=1024,
                                       use_early_stopping=False,
                                       device='cuda',
                                       model_input_column_list=['unit2_loc_minmax_norm', 'unit2to1_vector'],
                                       zero_pad_nonconsecutive=True,
                                       ends_input_with_out_len_zeros=False,
                                       seq_len=8,
                                       out_len=3,
                                       cnn_channels=[128, 128],
                                       rnn_num_layers=1,
                                       rnn_hidden_size=128,
                                       mlp_layer_sizes=[64],
                                       rnn_dropout=0, # fix
                                       cnn_dropout=0, # fix
                                       adam_weight_decay=0, # fix
                                       loss_func_name='cross-entropy-loss',
                                       adam_learning_rate=5e-4, # fix
                                       adam_opt_milestone_list=[12, 18],
                                       ), 
              experiment_config=ExperimentConfig(
                  exp_folder_name='00_test_drone_cnn_ed_rnn_experiment',
                  exp_dict={
                      "model_arch_name": ['cnn-ed-gru-model'
                                        ],
                       "num_classes": [32]
                  })).run()


2025-05-20 15:10:21.531 | DEBUG    | src.experiment:run:40 - updated model_config | model_arch_name to cnn-ed-gru-model
2025-05-20 15:10:21.532 | DEBUG    | src.experiment:run:36 - updated data_config |num_classes to 32
2025-05-20 15:10:21.532 | DEBUG    | src.experiment:run:40 - updated model_config | num_classes to 32
2025-05-20 15:10:21.532 | DEBUG    | src.experiment:run:40 - updated model_config | model_input_column_list to ['unit2_loc_minmax_norm', 'unit2to1_vector']
2025-05-20 15:10:42.757 | INFO     | src.data.dataprep:get_train_val_test_dataset:296 - 
Dataset is LOADED from f:/repo/gpsbeam\data/processed/Scenario23/dset_scenario23_seednum42_train0.65_test0.2_portion100_beam32_splitting_method_adjusted.hkl
2025-05-20 15:10:42.757 | INFO     | src.data.dataprep:get_train_val_test_dataset:311 - 
                    RAW DATASET INFO
                    ------------------------------
                    Scenario Num                                    : 23,
                    Split

Saving plot data to f:/repo/gpsbeam\data/experiment_result/00_test_drone_cnn_ed_rnn_experiment_20052025_151021\05-20-2025_15_10_42\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/00_test_drone_cnn_ed_rnn_experiment_20052025_151021\05-20-2025_15_10_42\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:14:18.105 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:14:18.124 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/00_test_drone_cnn_ed_rnn_experiment_20052025_151021\05-20-2025_15_10_42\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/00_test_drone_cnn_ed_rnn_experiment_20052025_151021\05-20-2025_15_10_42\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 45.75it/s]
2025-05-20 15:14:18.229 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.761 0.753 0.732 0.709]
 [0.973 0.978 0.974 0.953]
 [0.988 0.993 0.991 0.982]]
2025-05-20 15:14:23.942 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/00_test_drone_cnn_ed_rnn_experiment_20052025_151021\05-20-2025_15_10_42\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:14:24.175 | INFO 

In [3]:
fname = r'F:\repo\gpsbeam\data\experiment_result\00_test_drone_cnn_ed_rnn_experiment_20052025_151021\model_recap\exp_test_result_recap.csv'
df = pd.read_csv(fname)
# sort by pred0_top1_test_acc_percent
df = df.sort_values(by='pred0_top1_test_acc_percent', ascending=False)
df.head(15)

model_arch_name  num_classes  \
0  cnn-ed-gru-model           32   

                        model_input_column_list  scenario_num  avg_loss  \
0  ['unit2_loc_minmax_norm', 'unit2to1_vector']            23     1.475   

   model_size_MiB  pred0_top1_mean_power_loss_db  \
0            0.99                          0.299   

   pred1_top1_mean_power_loss_db  pred2_top1_mean_power_loss_db  \
0                          0.278                          0.272   

   pred3_top1_mean_power_loss_db  pred0_top1_n_beams_for_80pct_conf  \
0                          0.567                               1.56   

   pred1_top1_n_beams_for_80pct_conf  pred2_top1_n_beams_for_80pct_conf  \
0                              1.527                              1.533   

   pred3_top1_n_beams_for_80pct_conf  \
0                              1.542   

   pred0_top1_overhead_saving_for_80pct_conf  \
0                                     95.127   

   pred1_top1_overhead_saving_for_80pct_conf  \
0                                     95.227   

   pred2_top1_overhead_saving_for_80pct_conf  \
0                                     95.209   

   pred3_top1_overhead_saving_for_80pct_conf  \
0                                      95.18   

   pred0_top1_n_beams_for_85pct_conf  pred1_top1_n_beams_for_85pct_conf  \
0                              1.688                               1.66   

   pred2_top1_n_beams_for_85pct_conf  pred3_top1_n_beams_for_85pct_conf  \
0                              1.689                              1.718   

   pred0_top1_overhead_saving_for_85pct_conf  \
0                                     94.726   

   pred1_top1_overhead_saving_for_85pct_conf  \
0                                     94.811   

   pred2_top1_overhead_saving_for_85pct_conf  \
0                                     94.723   

   pred3_top1_overhead_saving_for_85pct_conf  \
0                                     94.631   

   pred0_top1_n_beams_for_90pct_conf  pred1_top1_n_beams_for_90pct_conf  \
0                              1.896                              1.844   

   pred2_top1_n_beams_for_90pct_conf  pred3_top1_n_beams_for_90pct_conf  \
0                              1.863                               1.89   

   pred0_top1_overhead_saving_for_90pct_conf  \
0                                     94.075   

   pred1_top1_overhead_saving_for_90pct_conf  \
0                                     94.236   

   pred2_top1_overhead_saving_for_90pct_conf  \
0                                     94.177   

   pred3_top1_overhead_saving_for_90pct_conf  \
0                                     94.093   

   pred0_top1_n_beams_for_95pct_conf  pred1_top1_n_beams_for_95pct_conf  \
0                              2.271                               2.21   

   pred2_top1_n_beams_for_95pct_conf  pred3_top1_n_beams_for_95pct_conf  \
0                              2.252                              2.294   

   pred0_top1_overhead_saving_for_95pct_conf  \
0                                     92.902   

   pred1_top1_overhead_saving_for_95pct_conf  \
0                                     93.093   

   pred2_top1_overhead_saving_for_95pct_conf  \
0                                     92.962   

   pred3_top1_overhead_saving_for_95pct_conf  \
0                                     92.831   

   pred0_top1_n_beams_for_99pct_conf  pred1_top1_n_beams_for_99pct_conf  \
0                               3.32                              3.319   

   pred2_top1_n_beams_for_99pct_conf  pred3_top1_n_beams_for_99pct_conf  \
0                               3.43                              3.496   

   pred0_top1_overhead_saving_for_99pct_conf  \
0                                     89.625   

   pred1_top1_overhead_saving_for_99pct_conf  \
0                                      89.63   

   pred2_top1_overhead_saving_for_99pct_conf  \
0                                      89.28   

   pred3_top1_overhead_saving_for_99pct_conf  \
0                                     89.075   

   pred0_top1_rel

# Check Vector Shape inside the model

In [4]:
import torch
from src.arch.cnn_ed_gru_model import CnnEdGruModel

# Create sample input
batch_size = 1
seq_len = 7
out_len = 3
feature_len = 5
x = torch.randn(batch_size, seq_len, feature_len)

# Initialize model
model = CnnEdGruModel(
    cnn_channels=[243, 243, 243],
    feature_len=feature_len,
    num_classes=64,
    rnn_num_layers=1,
    rnn_hidden_size=486,
    rnn_dropout=0.0,
    out_len=3,
    enable_logging=True
)

# Forward pass
output, hidden = model(x)



2025-05-20 15:19:12.599 | INFO     | src.arch.cnn_ed_gru_model:forward:109 - x shape: torch.Size([1, 7, 5])
2025-05-20 15:19:12.599 | INFO     | src.arch.cnn_ed_gru_model:forward:117 - x shape after reshape: torch.Size([1, 5, 7])
2025-05-20 15:19:12.599 | INFO     | src.arch.cnn_ed_gru_model:forward:129 - x shape after conv: torch.Size([1, 243, 7])
2025-05-20 15:19:12.599 | INFO     | src.arch.cnn_ed_gru_model:forward:135 - x shape after reshape: torch.Size([1, 7, 243])
2025-05-20 15:19:12.599 | INFO     | src.arch.cnn_ed_gru_model:forward:141 - encoder_output shape: torch.Size([1, 7, 486])
2025-05-20 15:19:12.599 | INFO     | src.arch.cnn_ed_gru_model:forward:142 - encoder_hidden shape: torch.Size([1, 1, 486])
2025-05-20 15:19:12.599 | INFO     | src.arch.cnn_ed_gru_model:forward:148 - decoder_input shape: torch.Size([1, 1, 486])
2025-05-20 15:19:12.599 | INFO     | src.arch.cnn_ed_gru_model:forward:154 - expanded_input shape: torch.Size([1, 4, 486])
2025-05-20 15:19:12.613 | INFO    