In [1]:
import sys
import pandas as pd
import numpy as np
from IPython.display import display
# do not truncate the dataframe column width
pd.options.display.max_colwidth = None
pd.options.display.max_columns = None

sys.path.append('F:/repo/gpsbeam')

from src.config.data_config import DataConfig
from src.config.cnn_ed_rnn_model_config import ModelConfig
from src.config.experiment_config import ExperimentConfig
from src.experiment import RunExperiment

def combined_metric(row):
    loss_db = np.mean(row['pred0_top1_mean_power_loss_db'] + row['pred1_top1_mean_power_loss_db']\
             + row['pred2_top1_mean_power_loss_db'] + row['pred3_top1_mean_power_loss_db'])
    accuracy = np.mean(row['pred0_top1_test_acc_percent'] + row['pred1_top1_test_acc_percent']\
                      + row['pred2_top1_test_acc_percent'] + row['pred3_top1_test_acc_percent']) / 100
    invert_loss_db = 1/loss_db
    return (invert_loss_db * 0.5) + (accuracy * 0.5)

def df_apply_combined_metric(df):
    key = 'combined_loss_db_and_acc'
    df[key] = df.apply(combined_metric, axis=1)
    df = df.sort_values(by=key, ascending=False)
    return df


# Sequence Length Variation

In [2]:
run_obj = RunExperiment(data_config =DataConfig(scenario_num=23,
                                                splitting_method='adjusted',
                                                train_val_test_split_frac=[0.65,0.15, 0.2],
                                                seednum=42
                                                ), 
              model_config=ModelConfig(model_arch_name='cnn-ed-gru-model',
                                       train_epoch=20,
                                       train_batch_size=8,
                                       test_batch_size=1024,
                                       use_early_stopping=False,
                                       device='cuda',
                                       model_input_column_list=['unit2_loc_minmax_norm', 'unit2to1_vector'],
                                       zero_pad_nonconsecutive=True,
                                       ends_input_with_out_len_zeros=False,
                                       seq_len=8,
                                       out_len=3,
                                       cnn_channels=[128, 128],
                                       rnn_num_layers=1,
                                       rnn_hidden_size=128,
                                       mlp_layer_sizes=[64],
                                       rnn_dropout=0, # fix
                                       cnn_dropout=0, # fix
                                       adam_weight_decay=0, # fix
                                       loss_func_name='cross-entropy-loss',
                                       adam_learning_rate=5e-4, # fix
                                       adam_opt_milestone_list=[12, 18],
                                       ),
              experiment_config=ExperimentConfig(
                  exp_folder_name='01_drone_cnn_ed_rnn_experiment_var_seq_len',
                  exp_dict={
                       "seq_len": [3, 4, 5, 6, 7, 8, 9],
                       "num_classes": [32]
                  })).run()

2025-05-20 15:10:40.645 | DEBUG    | src.experiment:run:40 - updated model_config | seq_len to 3
2025-05-20 15:10:40.646 | DEBUG    | src.experiment:run:36 - updated data_config |num_classes to 32
2025-05-20 15:10:40.646 | DEBUG    | src.experiment:run:40 - updated model_config | num_classes to 32
2025-05-20 15:10:40.646 | DEBUG    | src.experiment:run:40 - updated model_config | model_input_column_list to ['unit2_loc_minmax_norm', 'unit2to1_vector']
2025-05-20 15:11:01.822 | INFO     | src.data.dataprep:get_train_val_test_dataset:296 - 
Dataset is LOADED from f:/repo/gpsbeam\data/processed/Scenario23/dset_scenario23_seednum42_train0.65_test0.2_portion100_beam32_splitting_method_adjusted.hkl
2025-05-20 15:11:01.823 | INFO     | src.data.dataprep:get_train_val_test_dataset:311 - 
                    RAW DATASET INFO
                    ------------------------------
                    Scenario Num                                    : 23,
                    Splitting Method            

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_11_01\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_11_01\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:14:27.110 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:14:27.127 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_11_01\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_11_01\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 64.83it/s]
2025-05-20 15:14:27.209 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.745 0.761 0.767 0.727]
 [0.95  0.969 0.97  0.955]
 [0.991 0.994 0.992 0.986]]
2025-05-20 15:14:32.450 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_11_01\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:14:32.646 

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_14_32\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_14_32\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf
Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_14_32\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


2025-05-20 15:16:46.230 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:16:46.230 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_14_32\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth
test: 100%|██████████| 3/3 [00:00<00:00, 96.00it/s]
2025-05-20 15:16:46.313 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.733 0.761 0.747 0.717]
 [0.967 0.984 0.98  0.965]
 [0.992 0.995 0.995 0.988]]
2025-05-20 15:16:50.920 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_14_32\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_16_51\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_16_51\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf
Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_16_51\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


2025-05-20 15:18:52.205 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:18:52.225 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_16_51\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth
test: 100%|██████████| 3/3 [00:00<00:00, 64.00it/s]
2025-05-20 15:18:52.305 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.722 0.754 0.736 0.712]
 [0.977 0.983 0.978 0.964]
 [0.989 0.995 0.992 0.983]]
2025-05-20 15:18:58.085 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_16_51\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_18_58\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_18_58\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:21:05.212 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:21:05.227 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_18_58\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_18_58\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 81.00it/s]
2025-05-20 15:21:05.313 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.755 0.748 0.732 0.71 ]
 [0.972 0.984 0.978 0.963]
 [0.989 0.993 0.993 0.987]]
2025-05-20 15:21:09.832 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_18_58\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:21:09.951 

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_21_10\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_21_10\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:23:20.893 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:23:20.909 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_21_10\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_21_10\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 87.59it/s]
2025-05-20 15:23:20.984 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.761 0.751 0.724 0.702]
 [0.97  0.98  0.975 0.956]
 [0.984 0.994 0.99  0.982]]
2025-05-20 15:23:25.615 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_21_10\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:23:25.745 

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_23_25\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_23_25\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:25:34.447 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:25:34.447 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_23_25\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_23_25\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 80.58it/s]
2025-05-20 15:25:34.530 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.761 0.753 0.732 0.709]
 [0.973 0.978 0.974 0.953]
 [0.988 0.993 0.991 0.982]]
2025-05-20 15:25:39.168 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_23_25\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:25:39.322 

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_25_39\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_25_39\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:27:49.882 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:27:49.890 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_25_39\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_25_39\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 2/2 [00:00<00:00, 47.15it/s]
2025-05-20 15:27:49.979 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.77  0.771 0.75  0.721]
 [0.973 0.982 0.976 0.959]
 [0.986 0.991 0.987 0.979]]
2025-05-20 15:27:54.784 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\05-20-2025_15_25_39\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:27:54.972 

In [6]:
fname = r'F:\repo\gpsbeam\data\experiment_result\01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151040\model_recap\exp_test_result_recap.csv'
df = pd.read_csv(fname)
df = df_apply_combined_metric(df)
df

seq_len  num_classes                       model_input_column_list  \
0        3           32  ['unit2_loc_minmax_norm', 'unit2to1_vector']   
1        4           32  ['unit2_loc_minmax_norm', 'unit2to1_vector']   
2        5           32  ['unit2_loc_minmax_norm', 'unit2to1_vector']   
6        9           32  ['unit2_loc_minmax_norm', 'unit2to1_vector']   
5        8           32  ['unit2_loc_minmax_norm', 'unit2to1_vector']   
3        6           32  ['unit2_loc_minmax_norm', 'unit2to1_vector']   
4        7           32  ['unit2_loc_minmax_norm', 'unit2to1_vector']   

   scenario_num  avg_loss  model_size_MiB  pred0_top1_mean_power_loss_db  \
0            23     2.078            0.99                          0.279   
1            23     1.531            0.99                          0.287   
2            23     1.583            0.99                          0.237   
6            23     0.798            0.99                          0.280   
5            23     1.475            0.99                          0.299   
3            23     1.984            0.99                          0.358   
4            23     1.990            0.99                          0.327   

   pred1_top1_mean_power_loss_db  pred2_top1_mean_power_loss_db  \
0                          0.298                          0.264   
1                          0.232                          0.227   
2                          0.236                          0.230   
6                          0.254                          0.244   
5                          0.278                          0.272   
3                          0.295                          0.269   
4                          0.369                          0.342   

   pred3_top1_mean_power_loss_db  pred0_top1_n_beams_for_80pct_conf  \
0                          0.420                              1.713   
1                          0.492                              1.694   
2                          0.492                              1.649   
6                          0.665                              1.521   
5                          0.567                              1.560   
3                          0.487                              1.569   
4                          0.604                              1.539   

   pred1_top1_n_beams_for_80pct_conf  pred2_top1_n_beams_for_80pct_conf  \
0                              1.690                              1.690   
1                              1.702                              1.700   
2                              1.642                              1.668   
6                              1.499                              1.525   
5                              1.527                              1.533   
3                              1.547                              1.579   
4                              1.508                              1.524   

   pred3_top1_n_beams_for_80pct_conf  \
0                              1.685   
1                              1.704   
2                              1.682   
6                              1.540   
5                              1.542   
3                              1.588   
4                              1.534   

   pred0_top1_overhead_saving_for_80pct_conf  \
0                                     94.645   
1                                     94.707   
2                                     94.846   
6                                     95.245   
5                                     95.127   
3                                     95.096   
4                                     95.190   

   pred1_top1_overhead_saving_for_80pct_conf  \
0                                     94.719   
1                                     94.682   
2                                     94.870   
6                                     95.315   
5                                     95.227   
3                                     95.166   
4                                     95.288   

   pred2_to

# Feature Variation


In [3]:
run_obj = RunExperiment(data_config =DataConfig(scenario_num=23,
                                                splitting_method='adjusted',
                                                train_val_test_split_frac=[0.65,0.15, 0.2],
                                                seednum=42
                                                ), 
              model_config=ModelConfig(model_arch_name='cnn-ed-gru-model',
                                       train_epoch=20,
                                       train_batch_size=8,
                                       test_batch_size=1024,
                                       use_early_stopping=False,
                                       device='cuda',
                                       model_input_column_list=['unit2_loc_minmax_norm', 'unit2to1_vector'],
                                       zero_pad_nonconsecutive=True,
                                       ends_input_with_out_len_zeros=False,
                                       seq_len=8,
                                       out_len=3,
                                       cnn_channels=[128, 128],
                                       rnn_num_layers=1,
                                       rnn_hidden_size=128,
                                       mlp_layer_sizes=[64],
                                       rnn_dropout=0, # fix
                                       cnn_dropout=0, # fix
                                       adam_weight_decay=0, # fix
                                       loss_func_name='cross-entropy-loss',
                                       adam_learning_rate=5e-4, # fix
                                       adam_opt_milestone_list=[12, 18],
                                       ),
              experiment_config=ExperimentConfig(
                  exp_folder_name='01_drone_cnn_ed_rnn_experiment_var_feature_input',
                  exp_dict={
                       "model_input_column_list": [
                           ['unit2_loc_minmax_norm'], 
                           ['unit2to1_vector'],
                           ['unit2_loc_minmax_norm', 'unit2to1_vector'],        
                        #    ['unit1_beam_idx_32']
                           ],
                       "num_classes": [32]
                  })).run()

2025-05-20 15:27:55.338 | DEBUG    | src.experiment:run:40 - updated model_config | model_input_column_list to ['unit2_loc_minmax_norm']
2025-05-20 15:27:55.338 | DEBUG    | src.experiment:run:36 - updated data_config |num_classes to 32
2025-05-20 15:27:55.339 | DEBUG    | src.experiment:run:40 - updated model_config | num_classes to 32
2025-05-20 15:28:17.130 | INFO     | src.data.dataprep:get_train_val_test_dataset:296 - 
Dataset is LOADED from f:/repo/gpsbeam\data/processed/Scenario23/dset_scenario23_seednum42_train0.65_test0.2_portion100_beam32_splitting_method_adjusted.hkl
2025-05-20 15:28:17.130 | INFO     | src.data.dataprep:get_train_val_test_dataset:311 - 
                    RAW DATASET INFO
                    ------------------------------
                    Scenario Num                                    : 23,
                    Splitting Method                                : adjusted
                    Portion Percentage                              : 100
           

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152755\05-20-2025_15_28_17\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152755\05-20-2025_15_28_17\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:30:16.624 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:30:16.640 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152755\05-20-2025_15_28_17\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152755\05-20-2025_15_28_17\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 85.57it/s]
2025-05-20 15:30:16.726 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.648 0.637 0.634 0.625]
 [0.898 0.903 0.897 0.882]
 [0.967 0.971 0.969 0.966]]
2025-05-20 15:30:21.263 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152755\05-20-2025_15_28_17\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:30:2

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152755\05-20-2025_15_30_21\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152755\05-20-2025_15_30_21\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:32:23.136 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:32:23.152 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152755\05-20-2025_15_30_21\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152755\05-20-2025_15_30_21\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 85.16it/s]
2025-05-20 15:32:23.223 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.656 0.653 0.649 0.635]
 [0.928 0.945 0.946 0.935]
 [0.969 0.977 0.982 0.979]]
2025-05-20 15:32:27.757 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152755\05-20-2025_15_30_21\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:32:2

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152755\05-20-2025_15_32_27\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152755\05-20-2025_15_32_27\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:34:39.120 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:34:39.127 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152755\05-20-2025_15_32_27\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152755\05-20-2025_15_32_27\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 89.39it/s]
2025-05-20 15:34:39.188 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.761 0.753 0.732 0.709]
 [0.973 0.978 0.974 0.953]
 [0.988 0.993 0.991 0.982]]
2025-05-20 15:34:43.910 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152755\05-20-2025_15_32_27\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:34:4

In [7]:
fname = r'F:\repo\gpsbeam\data\experiment_result\01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152755\model_recap\exp_test_result_recap.csv'
df = pd.read_csv(fname)
df = df_apply_combined_metric(df)
df

model_input_column_list  num_classes  scenario_num  \
2  ['unit2_loc_minmax_norm', 'unit2to1_vector']           32            23   
0                     ['unit2_loc_minmax_norm']           32            23   
1                           ['unit2to1_vector']           32            23   

   avg_loss  model_size_MiB  pred0_top1_mean_power_loss_db  \
2     1.475            0.99                          0.299   
0     3.235            0.99                          0.726   
1     2.771            0.99                          1.471   

   pred1_top1_mean_power_loss_db  pred2_top1_mean_power_loss_db  \
2                          0.278                          0.272   
0                          0.805                          0.889   
1                          1.365                          1.301   

   pred3_top1_mean_power_loss_db  pred0_top1_n_beams_for_80pct_conf  \
2                          0.567                              1.560   
0                          1.224                              1.833   
1                          1.538                              2.081   

   pred1_top1_n_beams_for_80pct_conf  pred2_top1_n_beams_for_80pct_conf  \
2                              1.527                              1.533   
0                              1.838                              1.838   
1                              2.070                              2.075   

   pred3_top1_n_beams_for_80pct_conf  \
2                              1.542   
0                              1.838   
1                              2.089   

   pred0_top1_overhead_saving_for_80pct_conf  \
2                                     95.127   
0                                     94.273   
1                                     93.495   

   pred1_top1_overhead_saving_for_80pct_conf  \
2                                     95.227   
0                                     94.256   
1                                     93.532   

   pred2_top1_overhead_saving_for_80pct_conf  \
2                                     95.209   
0                                     94.256   
1                                     93.515   

   pred3_top1_overhead_saving_for_80pct_conf  \
2                                     95.180   
0                                     94.256   
1                                     93.473   

   pred0_top1_n_beams_for_85pct_conf  pred1_top1_n_beams_for_85pct_conf  \
2                              1.688                              1.660   
0                              2.029                              2.010   
1                              2.358                              2.327   

   pred2_top1_n_beams_for_85pct_conf  pred3_top1_n_beams_for_85pct_conf  \
2                              1.689                              1.718   
0                              2.033                              2.038   
1                              2.344                              2.368   

   pred0_top1_overhead_saving_for_85pct_conf  \
2                                     94.726   
0                                     93.660   
1                                     92.631   

   pred1_top1_overhead_saving_for_85pct_conf  \
2                                     94.811   
0                                     93.718   
1                                     92.729   

   pred2_top1_overhead_saving_for_85pct_conf  \
2                                     94.723   
0                                     93.646   
1                                     92.675   

   pred3_top1_overhead_saving_for_85pct_conf  \
2                                     94.631   
0                                     93.633   
1                                     92.599   

   pred0_top1_n_beams_for_90pct_conf  pred1_top1_n_beams_for_90pct_conf  \
2                              1.896                              1.844   
0                              2.302                              2.248   
1                              2.693                              2.658   


# Var Dataset Split Method

In [4]:
run_obj = RunExperiment(data_config =DataConfig(scenario_num=23,
                                                splitting_method='adjusted',
                                                train_val_test_split_frac=[0.65,0.15, 0.2],
                                                seednum=42
                                                ), 
              model_config=ModelConfig(model_arch_name='cnn-ed-gru-model',
                                       train_epoch=20,
                                       train_batch_size=8,
                                       test_batch_size=1024,
                                       use_early_stopping=False,
                                       device='cuda',
                                       model_input_column_list=['unit2_loc_minmax_norm', 'unit2to1_vector'],
                                       zero_pad_nonconsecutive=True,
                                       ends_input_with_out_len_zeros=False,
                                       seq_len=8,
                                       out_len=3,
                                       cnn_channels=[128, 128],
                                       rnn_num_layers=1,
                                       rnn_hidden_size=128,
                                       mlp_layer_sizes=[64],
                                       rnn_dropout=0, # fix
                                       cnn_dropout=0, # fix
                                       adam_weight_decay=0, # fix
                                       loss_func_name='cross-entropy-loss',
                                       adam_learning_rate=5e-4, # fix
                                       adam_opt_milestone_list=[12, 18],
                                       ),
              experiment_config=ExperimentConfig(
                  exp_folder_name='01_drone_cnn_ed_rnn_experiment_var_spliting_method',
                  exp_dict={
                       "splitting_method": [
                           "sequential",
                           "adjusted",
                           ],
                       "num_classes": [32]
                  })).run()

2025-05-20 15:34:44.410 | DEBUG    | src.experiment:run:36 - updated data_config |splitting_method to sequential
2025-05-20 15:34:44.410 | DEBUG    | src.experiment:run:36 - updated data_config |num_classes to 32
2025-05-20 15:34:44.410 | DEBUG    | src.experiment:run:40 - updated model_config | num_classes to 32
2025-05-20 15:34:44.410 | DEBUG    | src.experiment:run:40 - updated model_config | model_input_column_list to ['unit2_loc_minmax_norm', 'unit2to1_vector']
2025-05-20 15:34:44.410 | DEBUG    | src.data.dataprep:_check_path_availability:80 - File/Folder f:/repo/gpsbeam\data/raw/Scenario23/scenario23.csv is available.
2025-05-20 15:34:47.030 | DEBUG    | src.preprocessor.gpsprep:__init__:8 - GpsPrep Initialized.
2025-05-20 15:35:12.008 | INFO     | src.data.dataprep:_generate_train_val_test_dataset:335 - Generating train, validation and test datasets...
2025-05-20 15:35:26.119 | INFO     | src.data.dataprep:_save_to_hickle:589 - 
Train-Test dataset is SAVED as f:/repo/gpsbeam\da

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153444\05-20-2025_15_35_26\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_sequential.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153444\05-20-2025_15_35_26\dl_generated/model_measurement/label_distribution_scenario_23_sampling_sequential.pdf


2025-05-20 15:37:37.333 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:37:37.333 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153444\05-20-2025_15_35_26\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153444\05-20-2025_15_35_26\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 76.81it/s]
2025-05-20 15:37:37.416 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.418 0.404 0.4   0.396]
 [0.898 0.946 0.965 0.959]
 [0.998 0.998 0.998 0.997]]
2025-05-20 15:37:41.821 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153444\05-20-2025_15_35_26\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:37

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153444\05-20-2025_15_38_03\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153444\05-20-2025_15_38_03\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:40:05.314 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:40:05.314 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153444\05-20-2025_15_38_03\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153444\05-20-2025_15_38_03\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 89.88it/s]
2025-05-20 15:40:05.385 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.761 0.753 0.732 0.709]
 [0.973 0.978 0.974 0.953]
 [0.988 0.993 0.991 0.982]]
2025-05-20 15:40:09.484 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153444\05-20-2025_15_38_03\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:40

In [8]:
fname = r'F:\repo\gpsbeam\data\experiment_result\01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153444\model_recap\exp_test_result_recap.csv'
df = pd.read_csv(fname)
df = df_apply_combined_metric(df)
df

splitting_method  num_classes                       model_input_column_list  \
1         adjusted           32  ['unit2_loc_minmax_norm', 'unit2to1_vector']   
0       sequential           32  ['unit2_loc_minmax_norm', 'unit2to1_vector']   

   scenario_num  avg_loss  model_size_MiB  pred0_top1_mean_power_loss_db  \
1            23     1.475            0.99                          0.299   
0            23     1.586            0.99                          1.062   

   pred1_top1_mean_power_loss_db  pred2_top1_mean_power_loss_db  \
1                          0.278                          0.272   
0                          1.066                          1.073   

   pred3_top1_mean_power_loss_db  pred0_top1_n_beams_for_80pct_conf  \
1                          0.567                              1.560   
0                          1.101                              1.984   

   pred1_top1_n_beams_for_80pct_conf  pred2_top1_n_beams_for_80pct_conf  \
1                              1.527                              1.533   
0                              1.983                              2.038   

   pred3_top1_n_beams_for_80pct_conf  \
1                              1.542   
0                              2.065   

   pred0_top1_overhead_saving_for_80pct_conf  \
1                                     95.127   
0                                     93.800   

   pred1_top1_overhead_saving_for_80pct_conf  \
1                                     95.227   
0                                     93.804   

   pred2_top1_overhead_saving_for_80pct_conf  \
1                                     95.209   
0                                     93.631   

   pred3_top1_overhead_saving_for_80pct_conf  \
1                                     95.180   
0                                     93.548   

   pred0_top1_n_beams_for_85pct_conf  pred1_top1_n_beams_for_85pct_conf  \
1                              1.688                               1.66   
0                              2.224                               2.17   

   pred2_top1_n_beams_for_85pct_conf  pred3_top1_n_beams_for_85pct_conf  \
1                              1.689                              1.718   
0                              2.234                              2.273   

   pred0_top1_overhead_saving_for_85pct_conf  \
1                                     94.726   
0                                     93.051   

   pred1_top1_overhead_saving_for_85pct_conf  \
1                                     94.811   
0                                     93.218   

   pred2_top1_overhead_saving_for_85pct_conf  \
1                                     94.723   
0                                     93.019   

   pred3_top1_overhead_saving_for_85pct_conf  \
1                                     94.631   
0                                     92.898   

   pred0_top1_n_beams_for_90pct_conf  pred1_top1_n_beams_for_90pct_conf  \
1                              1.896                              1.844   
0                              2.526                              2.480   

   pred2_top1_n_beams_for_90pct_conf  pred3_top1_n_beams_for_90pct_conf  \
1                              1.863                              1.890   
0                              2.565                              2.608   

   pred0_top1_overhead_saving_for_90pct_conf  \
1                                     94.075   
0                                     92.108   

   pred1_top1_overhead_saving_for_90pct_conf  \
1                                     94.236   
0                                     92.250   

   pred2_top1_overhead_saving_for_90pct_conf  \
1                                     94.177   
0                                     91.986   

   pred3_top1_overhead_saving_for_90pct_conf  \
1                                     94.093   
0                                     91.852   

   pred0_top1_n_beams_for_95pct_conf  pred1_top1_n_beams_for_95pct_conf  \
1                              2.271           

# Var num_classes


In [5]:
run_obj = RunExperiment(data_config =DataConfig(scenario_num=23,
                                                splitting_method='adjusted',
                                                train_val_test_split_frac=[0.65,0.15, 0.2],
                                                seednum=42
                                                ), 
              model_config=ModelConfig(model_arch_name='cnn-ed-gru-model',
                                       train_epoch=20,
                                       train_batch_size=8,
                                       test_batch_size=1024,
                                       use_early_stopping=False,
                                       device='cuda',
                                       model_input_column_list=['unit2_loc_minmax_norm', 'unit2to1_vector'],
                                       zero_pad_nonconsecutive=True,
                                       ends_input_with_out_len_zeros=False,
                                       seq_len=8,
                                       out_len=3,
                                       cnn_channels=[128, 128],
                                       rnn_num_layers=1,
                                       rnn_hidden_size=128,
                                       mlp_layer_sizes=[64],
                                       rnn_dropout=0, # fix
                                       cnn_dropout=0, # fix
                                       adam_weight_decay=0, # fix
                                       loss_func_name='cross-entropy-loss',
                                       adam_learning_rate=5e-4, # fix
                                       adam_opt_milestone_list=[12, 18],
                                       ),
              experiment_config=ExperimentConfig(
                  exp_folder_name='01_drone_cnn_ed_rnn_experiment_var_num_classes',
                  exp_dict={
                       "num_classes": [8, 16, 32, 64]
                  })).run()


2025-05-20 15:40:09.919 | DEBUG    | src.experiment:run:36 - updated data_config |num_classes to 8
2025-05-20 15:40:09.919 | DEBUG    | src.experiment:run:40 - updated model_config | num_classes to 8
2025-05-20 15:40:09.919 | DEBUG    | src.experiment:run:40 - updated model_config | model_input_column_list to ['unit2_loc_minmax_norm', 'unit2to1_vector']
2025-05-20 15:40:31.374 | INFO     | src.data.dataprep:get_train_val_test_dataset:296 - 
Dataset is LOADED from f:/repo/gpsbeam\data/processed/Scenario23/dset_scenario23_seednum42_train0.65_test0.2_portion100_beam8_splitting_method_adjusted.hkl
2025-05-20 15:40:31.374 | INFO     | src.data.dataprep:get_train_val_test_dataset:311 - 
                    RAW DATASET INFO
                    ------------------------------
                    Scenario Num                                    : 23,
                    Splitting Method                                : adjusted
                    Portion Percentage                              :

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_40_31\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_40_31\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:42:31.410 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 8
2025-05-20 15:42:31.410 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_40_31\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_8_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_40_31\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 2/2 [00:00<00:00, 101.97it/s]
2025-05-20 15:42:31.477 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.88  0.881 0.864 0.859]
 [0.997 0.995 0.995 0.992]
 [1.    1.    1.    0.999]]
2025-05-20 15:42:35.414 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_40_31\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:42:35

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_43_14\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_43_14\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:45:10.586 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 16
2025-05-20 15:45:10.586 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_43_14\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_16_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_43_14\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 2/2 [00:00<00:00, 57.55it/s]
2025-05-20 15:45:10.654 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.841 0.86  0.86  0.843]
 [0.986 0.988 0.99  0.985]
 [0.994 0.993 0.996 0.995]]
2025-05-20 15:45:15.073 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_43_14\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:45:15.

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_45_37\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_45_37\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:47:33.538 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:47:33.545 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_45_37\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_45_37\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 59.49it/s]
2025-05-20 15:47:33.614 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.761 0.753 0.732 0.709]
 [0.973 0.978 0.974 0.953]
 [0.988 0.993 0.991 0.982]]
2025-05-20 15:47:38.200 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_45_37\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:47:38.

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_48_17\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_48_17\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:50:16.658 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 64
2025-05-20 15:50:16.675 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_48_17\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_64_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_48_17\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 83.08it/s]
2025-05-20 15:50:16.758 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.632 0.64  0.641 0.634]
 [0.913 0.931 0.929 0.91 ]
 [0.974 0.972 0.976 0.97 ]]
2025-05-20 15:50:21.595 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\05-20-2025_15_48_17\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:50:21.

In [9]:
fname = r'F:\repo\gpsbeam\data\experiment_result\01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154009\model_recap\exp_test_result_recap.csv'
df = pd.read_csv(fname)
# df = df_apply_combined_metric(df)
df

num_classes                       model_input_column_list  scenario_num  \
0            8  ['unit2_loc_minmax_norm', 'unit2to1_vector']            23   
1           16  ['unit2_loc_minmax_norm', 'unit2to1_vector']            23   
2           32  ['unit2_loc_minmax_norm', 'unit2to1_vector']            23   
3           64  ['unit2_loc_minmax_norm', 'unit2to1_vector']            23   

   avg_loss  model_size_MiB  pred0_top1_mean_power_loss_db  \
0     0.349            0.99                          0.232   
1     0.454            0.99                          0.292   
2     1.475            0.99                          0.299   
3     1.680            1.00                          0.310   

   pred1_top1_mean_power_loss_db  pred2_top1_mean_power_loss_db  \
0                          0.343                          0.521   
1                          0.238                          0.280   
2                          0.278                          0.272   
3                          0.231                          0.206   

   pred3_top1_mean_power_loss_db  pred0_top1_n_beams_for_80pct_conf  \
0                          0.731                              1.194   
1                          0.407                              1.258   
2                          0.567                              1.560   
3                          0.253                              2.094   

   pred1_top1_n_beams_for_80pct_conf  pred2_top1_n_beams_for_80pct_conf  \
0                              1.213                              1.233   
1                              1.255                              1.279   
2                              1.527                              1.533   
3                              2.063                              2.070   

   pred3_top1_n_beams_for_80pct_conf  \
0                              1.248   
1                              1.294   
2                              1.542   
3                              2.116   

   pred0_top1_overhead_saving_for_80pct_conf  \
0                                     85.077   
1                                     92.136   
2                                     95.127   
3                                     96.728   

   pred1_top1_overhead_saving_for_80pct_conf  \
0                                     84.841   
1                                     92.155   
2                                     95.227   
3                                     96.777   

   pred2_top1_overhead_saving_for_80pct_conf  \
0                                     84.593   
1                                     92.004   
2                                     95.209   
3                                     96.765   

   pred3_top1_overhead_saving_for_80pct_conf  \
0                                     84.401   
1                                     91.915   
2                                     95.180   
3                                     96.694   

   pred0_top1_n_beams_for_85pct_conf  pred1_top1_n_beams_for_85pct_conf  \
0                              1.235                              1.257   
1                              1.318                              1.317   
2                              1.688                              1.660   
3                              2.352                              2.318   

   pred2_top1_n_beams_for_85pct_conf  pred3_top1_n_beams_for_85pct_conf  \
0                              1.282                              1.298   
1                              1.329                              1.352   
2                              1.689                              1.718   
3                              2.341                              2.377   

   pred0_top1_overhead_saving_for_85pct_conf  \
0                                     84.562   
1                                     91.762   
2                                     94.726   
3                                     96.324   

   pred1_top1_overhead_saving_for_85pct_conf  \
0                          