In [1]:
import sys
import pandas as pd
import numpy as np
from IPython.display import display
# do not truncate the dataframe column width
pd.options.display.max_colwidth = None
pd.options.display.max_columns = None

sys.path.append('F:/repo/gpsbeam')

from src.config.data_config import DataConfig
from src.config.cnn_ed_rnn_model_config import ModelConfig
from src.config.experiment_config import ExperimentConfig
from src.experiment import RunExperiment

def combined_metric(row):
    loss_db = np.mean(row['pred0_top1_mean_power_loss_db'] + row['pred1_top1_mean_power_loss_db']\
             + row['pred2_top1_mean_power_loss_db'] + row['pred3_top1_mean_power_loss_db'])
    accuracy = np.mean(row['pred0_top1_test_acc_percent'] + row['pred1_top1_test_acc_percent']\
                      + row['pred2_top1_test_acc_percent'] + row['pred3_top1_test_acc_percent']) / 100
    invert_loss_db = 1/loss_db
    return (invert_loss_db * 0.5) + (accuracy * 0.5)

def df_apply_combined_metric(df):
    key = 'combined_loss_db_and_acc'
    df[key] = df.apply(combined_metric, axis=1)
    df = df.sort_values(by=key, ascending=False)
    return df


# Sequence Length Variation

In [2]:
run_obj = RunExperiment(data_config =DataConfig(scenario_num=23,
                                                splitting_method='adjusted',
                                                train_val_test_split_frac=[0.65,0.15, 0.2],
                                                seednum=42
                                                ), 
              model_config=ModelConfig(model_arch_name='cnn-ed-gru-model',
                                       train_epoch=20,
                                       train_batch_size=8,
                                       test_batch_size=1024,
                                       use_early_stopping=False,
                                       device='cuda',
                                       model_input_column_list=["unit2to1_vector", "unit2_height_log"],
                                       zero_pad_nonconsecutive=True,
                                       ends_input_with_out_len_zeros=False,
                                       seq_len=8,
                                       out_len=3,
                                       cnn_channels=[128, 128],
                                       rnn_num_layers=1,
                                       rnn_hidden_size=128,
                                       mlp_layer_sizes=[64],
                                       rnn_dropout=0, # fix
                                       cnn_dropout=0, # fix
                                       adam_weight_decay=0, # fix
                                       loss_func_name='cross-entropy-loss',
                                       adam_learning_rate=5e-4, # fix
                                       adam_opt_milestone_list=[12, 18],
                                       ),
              experiment_config=ExperimentConfig(
                  exp_folder_name='01_drone_cnn_ed_rnn_experiment_var_seq_len',
                  exp_dict={
                       "seq_len": [3, 4, 5, 6, 7, 8, 9],
                       "num_classes": [32]
                  })).run()

2025-05-20 15:11:28.733 | DEBUG    | src.experiment:run:40 - updated model_config | seq_len to 3
2025-05-20 15:11:28.733 | DEBUG    | src.experiment:run:36 - updated data_config |num_classes to 32
2025-05-20 15:11:28.734 | DEBUG    | src.experiment:run:40 - updated model_config | num_classes to 32
2025-05-20 15:11:28.735 | DEBUG    | src.experiment:run:40 - updated model_config | model_input_column_list to ['unit2to1_vector', 'unit2_height_log']
2025-05-20 15:11:51.689 | INFO     | src.data.dataprep:get_train_val_test_dataset:296 - 
Dataset is LOADED from f:/repo/gpsbeam\data/processed/Scenario23/dset_scenario23_seednum42_train0.65_test0.2_portion100_beam32_splitting_method_adjusted.hkl
2025-05-20 15:11:51.689 | INFO     | src.data.dataprep:get_train_val_test_dataset:311 - 
                    RAW DATASET INFO
                    ------------------------------
                    Scenario Num                                    : 23,
                    Splitting Method                 

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_11_51\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_11_51\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:15:26.772 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:15:26.788 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_11_51\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_11_51\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 81.78it/s]
2025-05-20 15:15:26.878 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.738 0.771 0.76  0.725]
 [0.956 0.967 0.959 0.945]
 [0.992 0.994 0.994 0.986]]
2025-05-20 15:15:31.560 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_11_51\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:15:31.746 

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_15_31\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_15_31\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:17:28.163 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:17:28.179 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_15_31\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_15_31\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 67.72it/s]
2025-05-20 15:17:28.254 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.738 0.755 0.736 0.701]
 [0.957 0.963 0.958 0.94 ]
 [0.992 0.996 0.994 0.986]]
2025-05-20 15:17:32.542 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_15_31\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:17:32.667 

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_17_32\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_17_32\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:19:31.431 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:19:31.449 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_17_32\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_17_32\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 72.91it/s]
2025-05-20 15:19:31.529 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.723 0.747 0.723 0.689]
 [0.95  0.956 0.95  0.935]
 [0.989 0.995 0.991 0.979]]
2025-05-20 15:19:36.236 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_17_32\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:19:36.382 

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_19_36\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_19_36\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:21:40.161 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:21:40.181 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_19_36\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_19_36\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 61.24it/s]
2025-05-20 15:21:40.262 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.717 0.735 0.713 0.67 ]
 [0.959 0.975 0.971 0.953]
 [0.987 0.991 0.989 0.981]]
2025-05-20 15:21:44.707 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_19_36\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:21:44.851 

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_21_44\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_21_44\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:23:54.177 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:23:54.186 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_21_44\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_21_44\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 84.92it/s]
2025-05-20 15:23:54.256 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.75  0.751 0.73  0.704]
 [0.945 0.956 0.947 0.93 ]
 [0.98  0.985 0.98  0.97 ]]
2025-05-20 15:23:58.861 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_21_44\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:23:58.998 

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_23_59\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_23_59\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:26:09.378 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:26:09.388 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_23_59\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_23_59\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 64.87it/s]
2025-05-20 15:26:09.464 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.753 0.767 0.75  0.715]
 [0.962 0.972 0.962 0.952]
 [0.985 0.99  0.987 0.977]]
2025-05-20 15:26:14.131 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_23_59\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:26:14.263 

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_26_14\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_26_14\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:28:27.717 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:28:27.734 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_26_14\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_26_14\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 2/2 [00:00<00:00, 39.94it/s]
2025-05-20 15:28:27.817 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.743 0.754 0.733 0.704]
 [0.953 0.966 0.952 0.933]
 [0.987 0.992 0.991 0.98 ]]
2025-05-20 15:28:32.939 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\05-20-2025_15_26_14\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:28:33.106 

In [6]:
fname = r'F:\repo\gpsbeam\data\experiment_result\01_drone_cnn_ed_rnn_experiment_var_seq_len_20052025_151128\model_recap\exp_test_result_recap.csv'
df = pd.read_csv(fname)
df = df_apply_combined_metric(df)
df

seq_len  num_classes                  model_input_column_list  \
0        3           32  ['unit2to1_vector', 'unit2_height_log']   
1        4           32  ['unit2to1_vector', 'unit2_height_log']   
2        5           32  ['unit2to1_vector', 'unit2_height_log']   
6        9           32  ['unit2to1_vector', 'unit2_height_log']   
5        8           32  ['unit2to1_vector', 'unit2_height_log']   
4        7           32  ['unit2to1_vector', 'unit2_height_log']   
3        6           32  ['unit2to1_vector', 'unit2_height_log']   

   scenario_num  avg_loss  model_size_MiB  pred0_top1_mean_power_loss_db  \
0            23     2.017            0.99                          0.249   
1            23     1.568            0.99                          0.247   
2            23     1.649            0.99                          0.278   
6            23     0.850            0.99                          0.298   
5            23     1.579            0.99                          0.328   
4            23     1.873            0.99                          0.369   
3            23     1.688            0.99                          0.414   

   pred1_top1_mean_power_loss_db  pred2_top1_mean_power_loss_db  \
0                          0.226                          0.242   
1                          0.241                          0.259   
2                          0.251                          0.285   
6                          0.288                          0.349   
5                          0.345                          0.397   
4                          0.381                          0.390   
3                          0.300                          0.299   

   pred3_top1_mean_power_loss_db  pred0_top1_n_beams_for_80pct_conf  \
0                          0.483                              1.785   
1                          0.586                              1.837   
2                          0.640                              1.856   
6                          0.763                              1.756   
5                          0.836                              1.907   
4                          0.782                              1.978   
3                          0.637                              1.855   

   pred1_top1_n_beams_for_80pct_conf  pred2_top1_n_beams_for_80pct_conf  \
0                              1.773                              1.771   
1                              1.822                              1.821   
2                              1.848                              1.851   
6                              1.728                              1.738   
5                              1.897                              1.900   
4                              1.971                              1.967   
3                              1.819                              1.811   

   pred3_top1_n_beams_for_80pct_conf  \
0                              1.768   
1                              1.820   
2                              1.858   
6                              1.743   
5                              1.904   
4                              1.968   
3                              1.810   

   pred0_top1_overhead_saving_for_80pct_conf  \
0                                     94.422   
1                                     94.260   
2                                     94.199   
6                                     94.512   
5                                     94.040   
4                                     93.819   
3                                     94.203   

   pred1_top1_overhead_saving_for_80pct_conf  \
0                                     94.460   
1                                     94.306   
2                                     94.226   
6                                     94.601   
5                                     94.073   
4                                     93.840   
3                                     94.315   

   pred2_top1_overhead_saving_for_80pct_conf  \
0  

# Feature Variation


In [3]:
run_obj = RunExperiment(data_config =DataConfig(scenario_num=23,
                                                splitting_method='adjusted',
                                                train_val_test_split_frac=[0.65,0.15, 0.2],
                                                seednum=42
                                                ), 
              model_config=ModelConfig(model_arch_name='cnn-ed-gru-model',
                                       train_epoch=20,
                                       train_batch_size=8,
                                       test_batch_size=1024,
                                       use_early_stopping=False,
                                       device='cuda',
                                       model_input_column_list=["unit2to1_vector", "unit2_height_log"],
                                       zero_pad_nonconsecutive=True,
                                       ends_input_with_out_len_zeros=False,
                                       seq_len=8,
                                       out_len=3,
                                       cnn_channels=[128, 128],
                                       rnn_num_layers=1,
                                       rnn_hidden_size=128,
                                       mlp_layer_sizes=[64],
                                       rnn_dropout=0, # fix
                                       cnn_dropout=0, # fix
                                       adam_weight_decay=0, # fix
                                       loss_func_name='cross-entropy-loss',
                                       adam_learning_rate=5e-4, # fix
                                       adam_opt_milestone_list=[12, 18],
                                       ),
              experiment_config=ExperimentConfig(
                  exp_folder_name='01_drone_cnn_ed_rnn_experiment_var_feature_input',
                  exp_dict={
                       "model_input_column_list": [
                           ['unit2_loc_minmax_norm'], 
                           ['unit2_height_log'],
                           ['unit2_height'],      
                           ["unit2to1_vector", "unit2_height"],                 
                           ["unit2to1_vector", "unit2_height_log"],
                        #    ['unit1_beam_idx_32']
                           ],
                       "num_classes": [32]
                  })).run()

2025-05-20 15:28:33.590 | DEBUG    | src.experiment:run:40 - updated model_config | model_input_column_list to ['unit2_loc_minmax_norm']
2025-05-20 15:28:33.590 | DEBUG    | src.experiment:run:36 - updated data_config |num_classes to 32
2025-05-20 15:28:33.590 | DEBUG    | src.experiment:run:40 - updated model_config | num_classes to 32
2025-05-20 15:28:55.330 | INFO     | src.data.dataprep:get_train_val_test_dataset:296 - 
Dataset is LOADED from f:/repo/gpsbeam\data/processed/Scenario23/dset_scenario23_seednum42_train0.65_test0.2_portion100_beam32_splitting_method_adjusted.hkl
2025-05-20 15:28:55.330 | INFO     | src.data.dataprep:get_train_val_test_dataset:311 - 
                    RAW DATASET INFO
                    ------------------------------
                    Scenario Num                                    : 23,
                    Splitting Method                                : adjusted
                    Portion Percentage                              : 100
           

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_28_55\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_28_55\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:30:58.051 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:30:58.051 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_28_55\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_28_55\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 90.95it/s]
2025-05-20 15:30:58.124 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.648 0.637 0.634 0.625]
 [0.898 0.903 0.897 0.882]
 [0.967 0.971 0.969 0.966]]
2025-05-20 15:31:02.772 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_28_55\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:31:0

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_31_02\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_31_02\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:32:57.437 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:32:57.437 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_31_02\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_31_02\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 256.56it/s]
2025-05-20 15:32:57.487 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.259 0.258 0.257 0.258]
 [0.489 0.489 0.49  0.498]
 [0.645 0.648 0.623 0.624]]
2025-05-20 15:33:01.983 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_31_02\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:33:

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_33_02\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_33_02\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:35:01.861 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:35:01.861 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_33_02\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_33_02\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 60.25it/s]
2025-05-20 15:35:01.946 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.26  0.26  0.258 0.258]
 [0.478 0.485 0.486 0.491]
 [0.634 0.638 0.63  0.631]]
2025-05-20 15:35:06.100 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_33_02\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:35:0

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_35_06\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_35_06\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf
Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_35_06\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


2025-05-20 15:37:18.413 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:37:18.414 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_35_06\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth
test: 100%|██████████| 3/3 [00:00<00:00, 89.83it/s]
2025-05-20 15:37:18.481 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.638 0.647 0.625 0.608]
 [0.913 0.932 0.925 0.914]
 [0.972 0.981 0.977 0.969]]
2025-05-20 15:37:23.119 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_35_06\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Lo

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_37_23\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_37_23\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:39:23.119 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:39:23.122 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_37_23\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_37_23\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 82.26it/s]
2025-05-20 15:39:23.192 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.753 0.767 0.75  0.715]
 [0.962 0.972 0.962 0.952]
 [0.985 0.99  0.987 0.977]]
2025-05-20 15:39:28.210 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\05-20-2025_15_37_23\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:39:2

In [7]:
fname = r'F:\repo\gpsbeam\data\experiment_result\01_drone_cnn_ed_rnn_experiment_var_feature_input_20052025_152833\model_recap\exp_test_result_recap.csv'
df = pd.read_csv(fname)
df = df_apply_combined_metric(df)
df

model_input_column_list  num_classes  scenario_num  \
4  ['unit2to1_vector', 'unit2_height_log']           32            23   
0                ['unit2_loc_minmax_norm']           32            23   
3      ['unit2to1_vector', 'unit2_height']           32            23   
2                         ['unit2_height']           32            23   
1                     ['unit2_height_log']           32            23   

   avg_loss  model_size_MiB  pred0_top1_mean_power_loss_db  \
4     1.579            0.99                          0.328   
0     3.235            0.99                          0.726   
3     1.929            0.99                          0.776   
2     2.560            0.99                          5.891   
1     2.659            0.99                          6.050   

   pred1_top1_mean_power_loss_db  pred2_top1_mean_power_loss_db  \
4                          0.345                          0.397   
0                          0.805                          0.889   
3                          0.729                          0.777   
2                          5.836                          5.797   
1                          5.981                          5.964   

   pred3_top1_mean_power_loss_db  pred0_top1_n_beams_for_80pct_conf  \
4                          0.836                              1.907   
0                          1.224                              1.833   
3                          1.109                              2.753   
2                          5.853                              9.134   
1                          5.933                              8.315   

   pred1_top1_n_beams_for_80pct_conf  pred2_top1_n_beams_for_80pct_conf  \
4                              1.897                              1.900   
0                              1.838                              1.838   
3                              2.708                              2.706   
2                              9.046                              9.061   
1                              8.132                              8.120   

   pred3_top1_n_beams_for_80pct_conf  \
4                              1.904   
0                              1.838   
3                              2.711   
2                              9.058   
1                              8.147   

   pred0_top1_overhead_saving_for_80pct_conf  \
4                                     94.040   
0                                     94.273   
3                                     91.396   
2                                     71.456   
1                                     74.017   

   pred1_top1_overhead_saving_for_80pct_conf  \
4                                     94.073   
0                                     94.256   
3                                     91.537   
2                                     71.732   
1                                     74.588   

   pred2_top1_overhead_saving_for_80pct_conf  \
4                                     94.061   
0                                     94.256   
3                                     91.544   
2                                     71.683   
1                                     74.623   

   pred3_top1_overhead_saving_for_80pct_conf  \
4                                     94.049   
0                                     94.256   
3                                     91.527   
2                                     71.694   
1                                     74.540   

   pred0_top1_n_beams_for_85pct_conf  pred1_top1_n_beams_for_85pct_conf  \
4                              2.084                              2.086   
0                              2.029                              2.010   
3                              3.187                              3.118   
2                             10.763                             10.655   
1                              9.726                              9.424   

   pred2_top1_n_beams_for_85pct_conf  pred3_top1_n_beams_for_85pct_conf  \
4  

# Var Dataset Split Method

In [4]:
run_obj = RunExperiment(data_config =DataConfig(scenario_num=23,
                                                splitting_method='adjusted',
                                                train_val_test_split_frac=[0.65,0.15, 0.2],
                                                seednum=42
                                                ), 
              model_config=ModelConfig(model_arch_name='cnn-ed-gru-model',
                                       train_epoch=20,
                                       train_batch_size=8,
                                       test_batch_size=1024,
                                       use_early_stopping=False,
                                       device='cuda',
                                       model_input_column_list=["unit2to1_vector", "unit2_height_log"],
                                       zero_pad_nonconsecutive=True,
                                       ends_input_with_out_len_zeros=False,
                                       seq_len=8,
                                       out_len=3,
                                       cnn_channels=[128, 128],
                                       rnn_num_layers=1,
                                       rnn_hidden_size=128,
                                       mlp_layer_sizes=[64],
                                       rnn_dropout=0, # fix
                                       cnn_dropout=0, # fix
                                       adam_weight_decay=0, # fix
                                       loss_func_name='cross-entropy-loss',
                                       adam_learning_rate=5e-4, # fix
                                       adam_opt_milestone_list=[12, 18],
                                       ),
              experiment_config=ExperimentConfig(
                  exp_folder_name='01_drone_cnn_ed_rnn_experiment_var_spliting_method',
                  exp_dict={
                       "splitting_method": [
                           "sequential",
                           "adjusted",
                           ],
                       "num_classes": [32]
                  })).run()

2025-05-20 15:39:28.744 | DEBUG    | src.experiment:run:36 - updated data_config |splitting_method to sequential
2025-05-20 15:39:28.744 | DEBUG    | src.experiment:run:36 - updated data_config |num_classes to 32
2025-05-20 15:39:28.744 | DEBUG    | src.experiment:run:40 - updated model_config | num_classes to 32
2025-05-20 15:39:28.744 | DEBUG    | src.experiment:run:40 - updated model_config | model_input_column_list to ['unit2to1_vector', 'unit2_height_log']
2025-05-20 15:39:50.304 | INFO     | src.data.dataprep:get_train_val_test_dataset:296 - 
Dataset is LOADED from f:/repo/gpsbeam\data/processed/Scenario23/dset_scenario23_seednum42_train0.65_test0.2_portion100_beam32_splitting_method_sequential_shuffle_False_.hkl
2025-05-20 15:39:50.304 | INFO     | src.data.dataprep:get_train_val_test_dataset:311 - 
                    RAW DATASET INFO
                    ------------------------------
                    Scenario Num                                    : 23,
                    

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153928\05-20-2025_15_39_50\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_sequential.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153928\05-20-2025_15_39_50\dl_generated/model_measurement/label_distribution_scenario_23_sampling_sequential.pdf


2025-05-20 15:41:51.036 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:41:51.053 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153928\05-20-2025_15_39_50\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153928\05-20-2025_15_39_50\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 88.97it/s]
2025-05-20 15:41:51.125 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.545 0.517 0.509 0.499]
 [0.942 0.946 0.941 0.934]
 [0.998 0.998 0.996 0.994]]
2025-05-20 15:41:55.763 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153928\05-20-2025_15_39_50\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:41

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153928\05-20-2025_15_42_17\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153928\05-20-2025_15_42_17\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf
Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153928\05-20-2025_15_42_17\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


2025-05-20 15:44:17.087 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:44:17.099 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153928\05-20-2025_15_42_17\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth
test: 100%|██████████| 3/3 [00:00<00:00, 64.95it/s]
2025-05-20 15:44:17.168 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.753 0.767 0.75  0.715]
 [0.962 0.972 0.962 0.952]
 [0.985 0.99  0.987 0.977]]
2025-05-20 15:44:21.354 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153928\05-20-2025_15_42_17\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppDat

In [8]:
fname = r'F:\repo\gpsbeam\data\experiment_result\01_drone_cnn_ed_rnn_experiment_var_spliting_method_20052025_153928\model_recap\exp_test_result_recap.csv'
df = pd.read_csv(fname)
df = df_apply_combined_metric(df)
df

splitting_method  num_classes                  model_input_column_list  \
1         adjusted           32  ['unit2to1_vector', 'unit2_height_log']   
0       sequential           32  ['unit2to1_vector', 'unit2_height_log']   

   scenario_num  avg_loss  model_size_MiB  pred0_top1_mean_power_loss_db  \
1            23     1.579            0.99                          0.328   
0            23     1.338            0.99                          0.434   

   pred1_top1_mean_power_loss_db  pred2_top1_mean_power_loss_db  \
1                          0.345                          0.397   
0                          0.469                          0.555   

   pred3_top1_mean_power_loss_db  pred0_top1_n_beams_for_80pct_conf  \
1                          0.836                              1.907   
0                          0.641                              2.771   

   pred1_top1_n_beams_for_80pct_conf  pred2_top1_n_beams_for_80pct_conf  \
1                              1.897                              1.900   
0                              2.755                              2.628   

   pred3_top1_n_beams_for_80pct_conf  \
1                              1.904   
0                              2.665   

   pred0_top1_overhead_saving_for_80pct_conf  \
1                                     94.040   
0                                     91.341   

   pred1_top1_overhead_saving_for_80pct_conf  \
1                                     94.073   
0                                     91.392   

   pred2_top1_overhead_saving_for_80pct_conf  \
1                                     94.061   
0                                     91.788   

   pred3_top1_overhead_saving_for_80pct_conf  \
1                                     94.049   
0                                     91.672   

   pred0_top1_n_beams_for_85pct_conf  pred1_top1_n_beams_for_85pct_conf  \
1                              2.084                              2.086   
0                              3.230                              3.189   

   pred2_top1_n_beams_for_85pct_conf  pred3_top1_n_beams_for_85pct_conf  \
1                              2.095                              2.104   
0                              3.176                              3.164   

   pred0_top1_overhead_saving_for_85pct_conf  \
1                                     93.488   
0                                     89.905   

   pred1_top1_overhead_saving_for_85pct_conf  \
1                                     93.482   
0                                     90.035   

   pred2_top1_overhead_saving_for_85pct_conf  \
1                                     93.454   
0                                     90.075   

   pred3_top1_overhead_saving_for_85pct_conf  \
1                                     93.425   
0                                     90.111   

   pred0_top1_n_beams_for_90pct_conf  pred1_top1_n_beams_for_90pct_conf  \
1                              2.393                              2.394   
0                              3.803                              3.775   

   pred2_top1_n_beams_for_90pct_conf  pred3_top1_n_beams_for_90pct_conf  \
1                              2.394                              2.396   
0                              3.765                              3.768   

   pred0_top1_overhead_saving_for_90pct_conf  \
1                                     92.523   
0                                     88.115   

   pred1_top1_overhead_saving_for_90pct_conf  \
1                                     92.518   
0                                     88.203   

   pred2_top1_overhead_saving_for_90pct_conf  \
1                                     92.520   
0                                     88.234   

   pred3_top1_overhead_saving_for_90pct_conf  \
1                                     92.512   
0                                     88.226   

   pred0_top1_n_beams_for_95pct_conf  pred1_top1_n_beams_for_95pct_conf  \
1                              2.996                          

# Var num_classes


In [5]:
run_obj = RunExperiment(data_config =DataConfig(scenario_num=23,
                                                splitting_method='adjusted',
                                                train_val_test_split_frac=[0.65,0.15, 0.2],
                                                seednum=42
                                                ), 
              model_config=ModelConfig(model_arch_name='cnn-ed-gru-model',
                                       train_epoch=20,
                                       train_batch_size=8,
                                       test_batch_size=1024,
                                       use_early_stopping=False,
                                       device='cuda',
                                       model_input_column_list=["unit2to1_vector", "unit2_height_log"],
                                       zero_pad_nonconsecutive=True,
                                       ends_input_with_out_len_zeros=False,
                                       seq_len=8,
                                       out_len=3,
                                       cnn_channels=[128, 128],
                                       rnn_num_layers=1,
                                       rnn_hidden_size=128,
                                       mlp_layer_sizes=[64],
                                       rnn_dropout=0, # fix
                                       cnn_dropout=0, # fix
                                       adam_weight_decay=0, # fix
                                       loss_func_name='cross-entropy-loss',
                                       adam_learning_rate=5e-4, # fix
                                       adam_opt_milestone_list=[12, 18],
                                       ),
              experiment_config=ExperimentConfig(
                  exp_folder_name='01_drone_cnn_ed_rnn_experiment_var_num_classes',
                  exp_dict={
                       "num_classes": [8, 16, 32, 64]
                  })).run()


2025-05-20 15:44:21.888 | DEBUG    | src.experiment:run:36 - updated data_config |num_classes to 8
2025-05-20 15:44:21.888 | DEBUG    | src.experiment:run:40 - updated model_config | num_classes to 8
2025-05-20 15:44:21.888 | DEBUG    | src.experiment:run:40 - updated model_config | model_input_column_list to ['unit2to1_vector', 'unit2_height_log']
2025-05-20 15:44:43.356 | INFO     | src.data.dataprep:get_train_val_test_dataset:296 - 
Dataset is LOADED from f:/repo/gpsbeam\data/processed/Scenario23/dset_scenario23_seednum42_train0.65_test0.2_portion100_beam8_splitting_method_adjusted.hkl
2025-05-20 15:44:43.356 | INFO     | src.data.dataprep:get_train_val_test_dataset:311 - 
                    RAW DATASET INFO
                    ------------------------------
                    Scenario Num                                    : 23,
                    Splitting Method                                : adjusted
                    Portion Percentage                              : 100


Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_44_43\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_44_43\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:46:36.989 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 8
2025-05-20 15:46:37.005 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_44_43\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_8_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_44_43\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 2/2 [00:00<00:00, 59.30it/s]
2025-05-20 15:46:37.074 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.868 0.872 0.856 0.84 ]
 [0.997 0.997 0.995 0.993]
 [1.    1.    0.999 0.998]]
2025-05-20 15:46:41.209 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_44_43\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:46:41.

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_47_03\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_47_03\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:48:47.436 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 16
2025-05-20 15:48:47.436 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_47_03\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_16_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_47_03\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 2/2 [00:00<00:00, 57.01it/s]
2025-05-20 15:48:47.504 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.824 0.838 0.825 0.797]
 [0.985 0.985 0.986 0.98 ]
 [0.995 0.992 0.995 0.992]]
2025-05-20 15:48:51.873 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_47_03\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:48:52.

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_49_13\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_49_13\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:51:07.465 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 32
2025-05-20 15:51:07.471 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_49_13\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_32_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_49_13\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 60.07it/s]
2025-05-20 15:51:07.543 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.753 0.767 0.75  0.715]
 [0.962 0.972 0.962 0.952]
 [0.985 0.99  0.987 0.977]]
2025-05-20 15:51:11.635 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_49_13\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:51:11.

Saving plot data to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_51_33\dl_generated/model_measurement/label_distribution_data_scenario_23_sampling_adjusted.csv
Saving plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_51_33\dl_generated/model_measurement/label_distribution_scenario_23_sampling_adjusted.pdf


2025-05-20 15:53:13.284 | DEBUG    | src.modelprep:_load_best_checkpoint:550 - Get Model: cnn-ed-gru-model
                         NUM CLASSES: 64
2025-05-20 15:53:13.284 | INFO     | src.modelprep:_load_best_checkpoint:553 - Model loaded from f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_51_33\dl_generated/model_checkpoint/arch_cnn-ed-gru-model_nclass_64_.pth


Saved plot to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_51_33\dl_generated/model_measurement/train_val_loss_vs_epochs.pdf


test: 100%|██████████| 3/3 [00:00<00:00, 56.47it/s]
2025-05-20 15:53:13.382 | DEBUG    | src.utils.metric_handler:calculate_final_metrics_batch_first:81 - 
[[0.571 0.61  0.601 0.571]
 [0.902 0.907 0.907 0.893]
 [0.96  0.964 0.965 0.958]]
2025-05-20 15:53:17.488 | INFO     | src.modelprep:_save_inference_detail:661 - Saved inference detail to f:/repo/gpsbeam\data/experiment_result/01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\05-20-2025_15_51_33\dl_generated/model_inference_result/test_epoch_00_inference_detail.csv
c:\Users\vendi\AppData\Local\pypoetry\Cache\virtualenvs\geobeam-3fwD9wo9-py3.9\lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
2025-05-20 15:53:17.

In [9]:
fname = r'F:\repo\gpsbeam\data\experiment_result\01_drone_cnn_ed_rnn_experiment_var_num_classes_20052025_154421\model_recap\exp_test_result_recap.csv'
df = pd.read_csv(fname)
# df = df_apply_combined_metric(df)
df

num_classes                  model_input_column_list  scenario_num  \
0            8  ['unit2to1_vector', 'unit2_height_log']            23   
1           16  ['unit2to1_vector', 'unit2_height_log']            23   
2           32  ['unit2to1_vector', 'unit2_height_log']            23   
3           64  ['unit2to1_vector', 'unit2_height_log']            23   

   avg_loss  model_size_MiB  pred0_top1_mean_power_loss_db  \
0     0.374            0.99                          0.362   
1     0.502            0.99                          0.318   
2     1.579            0.99                          0.328   
3     2.199            1.00                          0.534   

   pred1_top1_mean_power_loss_db  pred2_top1_mean_power_loss_db  \
0                          0.387                          0.513   
1                          0.306                          0.424   
2                          0.345                          0.397   
3                          0.377                          0.425   

   pred3_top1_mean_power_loss_db  pred0_top1_n_beams_for_80pct_conf  \
0                          0.897                              1.223   
1                          0.596                              1.357   
2                          0.836                              1.907   
3                          0.524                              2.496   

   pred1_top1_n_beams_for_80pct_conf  pred2_top1_n_beams_for_80pct_conf  \
0                              1.235                              1.248   
1                              1.364                              1.375   
2                              1.897                              1.900   
3                              2.513                              2.548   

   pred3_top1_n_beams_for_80pct_conf  \
0                              1.256   
1                              1.388   
2                              1.904   
3                              2.576   

   pred0_top1_overhead_saving_for_80pct_conf  \
0                                     84.717   
1                                     91.519   
2                                     94.040   
3                                     96.099   

   pred1_top1_overhead_saving_for_80pct_conf  \
0                                     84.556   
1                                     91.473   
2                                     94.073   
3                                     96.074   

   pred2_top1_overhead_saving_for_80pct_conf  \
0                                     84.395   
1                                     91.406   
2                                     94.061   
3                                     96.019   

   pred3_top1_overhead_saving_for_80pct_conf  \
0                                     84.302   
1                                     91.323   
2                                     94.049   
3                                     95.975   

   pred0_top1_n_beams_for_85pct_conf  pred1_top1_n_beams_for_85pct_conf  \
0                              1.317                              1.331   
1                              1.455                              1.457   
2                              2.084                              2.086   
3                              2.829                              2.854   

   pred2_top1_n_beams_for_85pct_conf  pred3_top1_n_beams_for_85pct_conf  \
0                              1.339                              1.339   
1                              1.475                              1.485   
2                              2.095                              2.104   
3                              2.905                              2.942   

   pred0_top1_overhead_saving_for_85pct_conf  \
0                                     83.534   
1                                     90.909   
2                                     93.488   
3                                     95.579   

   pred1_top1_overhead_saving_for_85pct_conf  \
0                                     83.360   
1   